### ISSUE TITLE
Best practise to create a continous subscription

### ISSUE THREAD

**Issue by Konafets** [gerardojbaez/laraplans#10]
Hi,

in my application users should be able to subscribe to a montly plan and the subscription should get renewed every month until they cancel. 

The workflow should be like:
1. User subscribes to ProPlan
2. User gets the ability to use the ProPlans features
3. User gets invoiced (not part of the package but belongs to the workflow)
4. User uses the service for one month
5. Subscription of the user gets renewed (end date is set to next month)
6. User gets a new invoice
...
N. User cancels the plan
N+1. Subscription is valid until end of the interval
N+2. After subscription endet, User falls back to BasicPlan

I found the `renew()` method but this will reset the feature usage data, which is not what I want. Or should I consider every month as a new subscription?

**Comment by gerardojbaez** [comment]
You can override the `renew()` method on the subscription model and that way apply the appropriate logic. 

Clearing subscription usage data when a subscription is renewed should be optional. I'll add a configuration for this soon.

Creating a new subscription every month is another possibility, but I think it's a problem to manage.

**Comment by Konafets** [comment]
Thanks for the answer. I used my own implementation of `renew()`.
