### ISSUE TITLE
BC: Rename boolean methods of PlanSubscription

### ISSUE THREAD

**Issue by Konafets** [gerardojbaez/laraplans#11]
I propose the renaming of the following methods from `PlanSubscription`:
* `active()` to `isActive()`
* `onTrial()` to `isOnTrial()`
* `canceled()` to `isCanceled()`
* `ended()` to `hasEnded()`

This has two reasons:

1. It is a convention to have these kind of methods prefixed with `is` or `has`
2. The current naming interferres with the scope feature. I want to create a scope `scopeCanceled()` which will be used like this:

```
$canceledSubscriptions = Subscription::canceled()->get();
```

I can not do that currently because of the `canceled()` method. This will be called instead of the scope.

This is a BC break.

**Comment by gerardojbaez** [comment]
I agree, can be added for v2.

Thanks!
