### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by stanwarri** [gerardojbaez/laraplans#13]
If the feature value is not numeric or not one of the positive words, you get this error below when using `canUse()`

```
ErrorException in SubscriptionAbility.php line 83: 
A non-numeric value encountered

```

**Comment by gerardojbaez** [comment]
Will check that out and apply a fix if necessary. Thanks!

**Comment by gerardojbaez** [comment]
Can't replicate the problem. What PHP version are you using? What's the non-numeric value used?

**Comment by gerardojbaez** [comment]
I will close the issue as no additional information was received.
