### ISSUE TITLE
Method isFree will always return false

### ISSUE THREAD

**Issue by duckzland** [gerardojbaez/laraplans#2]
judging from the code : 

`    /**
     * Check if plan is free.
     *
     * @return boolean
     */
    public function isFree()
    {
        return ($this->price === 0.00 OR $this->price < 0.00);
    }`

it will always return false since $this->price is cast as string while 0.00 is not considered as string

**Comment by gerardojbaez** [comment]
You're right. The weird part is that tests run without any error. I've changed the code to: 

```php
return ((float) $this->price <= 0.00);
```

Tests passed without problem. 

Thanks!
