### ISSUE TITLE
in laravel 5.5 not working, can you update plz

### ISSUE THREAD

**Issue by pay2all** [gerardojbaez/laraplans#24]
in laravel 5.5 not working, can you update plz

**Comment by oanhnn** [comment]
+1

**Comment by siarheipashkevich** [comment]
@pay2all, @oanhnn could we please confirm that this problem has been fixed?

**Comment by gerardojbaez** [comment]
What errors are you guys experiencing? Is it the same reported in #26? 

I'm using Laraplans (dev-master) on a project using Laravel 5.5, all tests are passing; maybe the fix is already in place (7f8c23b95788da9a09a0cbe17bea3de5da83a63e), but has not been released yet.

**Comment by sanjaylive** [comment]
<img width="1141" alt="screen shot 2018-01-04 at 4 11 07 pm" src="https://user-images.githubusercontent.com/30732683/34560009-2c235f84-f16a-11e7-9200-49213807fae8.png">

**Comment by gerardojbaez** [comment]
Thanks, @sanjaylive. There's already a commit that solves this error... I will create a release soon. If you are still under development, you can try `dev-master` to try things out.

**Comment by siarheipashkevich** [comment]
I've the same issue in laravel 5.5.

**Comment by sanjaylive** [comment]
check update, already solved

**Comment by siarheipashkevich** [comment]
I've switched to `dev-master` and problem was fixed. But I think we should create a new release.

**Comment by josteph** [comment]
Please see to this issue (if you're not using `dev-master`) for the fix. #30

**Comment by oanhnn** [comment]
You can try my package [oanhnn/laravel-pricing-plans](https://github.com/oanhnn/laravel-pricing-plans)

**Comment by josteph** [comment]
@oanhnn You could have forked this package from @gerardojbaez rather than claiming it as your own.

**Comment by oanhnn** [comment]
@josteph Yes, it is a fork, but the license of @gerardojbaez 's package is MIT and i did refactor it  😄

**Comment by gerardojbaez** [comment]
@oanhnn, Having the [MIT license](https://opensource.org/licenses/MIT) doesn't mean you can claim it as yours; it clearly says that you have to preserve the Copyright along with the provided License. Please make the necessary adjustments to your repository. Refactoring someone else code doesn't make it yours.

**Comment by oanhnn** [comment]
@gerardojbaez 
I know my project the development on your project and your solution. Thank you very much about it.. But actually I have developed it on my idea and solution from mid-2017. You can now see it is different very much with your project.
However, I have linked to your project as the source of the project and added your name to the license in commit [afe05cee6fd1c0b1e9f5fbfe672f48dd2cbb4967](https://github.com/oanhnn/laravel-pricing-plans/commit/afe05cee6fd1c0b1e9f5fbfe672f48dd2cbb4967)

**Comment by gerardojbaez** [comment]
@oanhnn, Thanks for the adjustments. Your project is base on Laraplans, it doesn't matter if you have refactored it or built on top of it, the original Copyright must be included (and you already did). More information [here](https://softwareengineering.stackexchange.com/questions/157968/how-to-manage-a-copyright-notice-in-an-open-source-project).

**This is how I would do it (it is more explicit):**

```
Original work Copyright © 2016 Gerardo Baez <g@gerardobaez.com>
Modified work Copyright © 2017-2018 Oanh Nguyen <oanhnn.bk@gmail.com> 
```

**Comment by gerardojbaez** [comment]
The release is out! v2.2.0
