### ISSUE TITLE
Updating guide for new version

### ISSUE THREAD

**Issue by siarheipashkevich** [gerardojbaez/laraplans#25]
@gerardojbaez it will be better to create an updating guide for newly versions in future or create an update scripts as in `laratrust` package.

There are a few breaking changes in new version:
you added `canceled_immediately` to 'plan_subscriptions' table;
you changed `user_id` in 'plan_subscriptions' to 'morph';

Could you please describe the other possible breaking changes?

**Comment by gerardojbaez** [comment]
Polymorphic relations was introduced in version 2.0.0; a major release. This change was needed to properly fix #18. Besides this change and what you have listed, there's no other breaking change in 2.1.0. Please review the ["Changed" section under v2.1.0 in Changelog](https://github.com/gerardojbaez/laraplans/blob/master/CHANGELOG.md#210---2017-11-27); changes were made internally to some functions. 

Regarding having an Update Guide, this is a good idea and will be considered for future *major* releases.
