### ISSUE TITLE
 BindingResolutionException 

### ISSUE THREAD

**Issue by basarozcan** [gerardojbaez/laraplans#26]
Here is the error:
BindingResolutionException                                                                          
Unresolvable dependency resolving [Parameter #0 [ <required> $user ]] in class Gerardojbaez\Laraplans\SubscriptionBuilder
--
in Container.php (line 910)

Here is the code:
> 
> public function index()
>     {
>         $user = Auth::user();
>         $plan = Plan::find(1);
>         $user->newSubscription('main', $plan)->create();
>     }

I added _use Gerardojbaez\Laraplans\Models\Plan;_ in beginning of the controller but it never worked. Could you please help me?

**Comment by gerardojbaez** [comment]
What Laravel version are you using?

**Comment by basarozcan** [comment]
I'm using 5.4

**Comment by gerardojbaez** [comment]
There's a commit already in the repository (7f8c23b95788da9a09a0cbe17bea3de5da83a63e) but has not been released yet; it will be soon!

**Comment by AFZidan** [comment]
I have same issue 
`Unresolvable dependency resolving [Parameter #0 [ <required> $user ]] in class Gerardojbaez\Laraplans\SubscriptionBuilder`
with laravel 5.5

**Comment by josteph** [comment]
The fix is here. #30

**Comment by gerardojbaez** [comment]
The release is out: v2.2.0
