### ISSUE TITLE
Add methods to plan to retrieve informations about the features

### ISSUE THREAD

**Issue by Konafets** [gerardojbaez/laraplans#3]
Imagine you have a list of plans and want to display the name of the plan, the price and the amount of pictures a user can upload pro plan.

Title | Price | Amount of pictures
------------ | -------------: | ---------------
Basic | 0.00 | 10
Pro | 10.00 | 20

The Features were created like this:

```php
$planBasic = Plan::create([
    'name' => 'Basic',
    'price' => 0.00,
]);

$planBasic->features()->save(
    new PlanFeature(['code' => 'amount_of_pics', 'value' => 10, 'sort_order' => 1])
);
```

```php
$planPro = Plan::create([
    'name' => 'Pro',
    'price' => 10.00,
]);

$planPro->features()->save(
    new PlanFeature(['code' => 'amount_of_pics', 'value' => 20, 'sort_order' => 2])
);
```

It would be nice to have a method at the plan model which returns the value of a feature found by its code. Here is my implementation and usage:

```php
    /**
     * @return integer
     */
    public function getPicturesAttribute() : int 
    {
        return (int) $this->getFeatureByCode('amount_of_pics')->value;
    }

    /**
     * @param String $code
     * @return PlanFeature
     */
    public function getFeatureByCode(String $code) : PlanFeature
    {
        return $this->features()->getEager()->first(function($item) use ($code) {
            return $item->code === $code;
        });
    }
```

If you interested in this, I'll open a PR.

**Comment by gerardojbaez** [comment]
A method like your `getFeatureByCode` will be helpful. I don't think that feature specific getters (like your `getPicturesAttribute` should be implemented to Laraplans. Plan's features vary for each application. :)

**Comment by Konafets** [comment]
The `getPicturesAttribute()` was just an illustration of how the other method might be helpful.
