### ISSUE TITLE
Wrong plan subscription column reference for user

### ISSUE THREAD

**Issue by samtoya** [gerardojbaez/laraplans#30]
The method **(byUser)** in the PlanSubscription model has the wrong reference to the database column, 

You used **user_id** instead of **subscribable_id**

It's on line 317 in the PlanSubscription model, please fix this in your next update.

I'll share with you how I'm using the package when I'm done with my project.

Thanks.

**Comment by gerardojbaez** [comment]
Thanks for your bug report!
