### ISSUE TITLE
SubscriptionPlanChanged event confusion

### ISSUE THREAD

**Issue by bgultekin** [gerardojbaez/laraplans#36]
Hi, 
First of all, thanks for great package, it saved a lot of time.

When I created a new subscription, both SubscriptionCreated and SubscriptionPlanChanged events are fired. Shouldn't it be just SubscriptionCreated event?

Normally, I expect SubscriptionPlanChanged event fired when change of existing subscription.

**Comment by gerardojbaez** [comment]
You are totally right and once again, thanks for the pull request!
