### ISSUE TITLE
PHP Fatal error:  Trait method newSubscription has not been applied

### ISSUE THREAD

**Issue by wisusdev** [gerardojbaez/laraplans#38]
Trait method newSubscription has not been applied, because there are collisions with other trait methods on App\User  

User Model

**use Laravel\Cashier\Billable;**
use Illuminate\Notifications\Notifiable;
use Lexx\ChatMessenger\Traits\Messagable;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Gerardojbaez\Laraplans\Contracts\PlanSubscriberInterface;
use Gerardojbaez\Laraplans\Traits\PlanSubscriber;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements PlanSubscriberInterface
{
    use PlanSubscriber, Notifiable, EntrustUserTrait, **Billable**, Messagable;
}

The conflict is with Cashier, can it be solved?

**Comment by gerardojbaez** [comment]
Laraplans shouldn't be used with Cashier; you should use one of the two.

If you really want to use both of them, you will need to choose one of the two `newSubscriptions` methods. 

See the [PHP's documentation website for Trait method conflicts](http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict).
