### ISSUE TITLE
Question - valid_until vs ends_at

### ISSUE THREAD

**Issue by llioor** [gerardojbaez/laraplans#41]
Hi guys,
Someone can explain what is the usage/differences of:
PlanSubscription "ends_at" attribute and PlanSubscriptionUsage "valid_until" attribute.

I understood that the PlanSubscription talks about the subscription itself when the PlanSubscriptionUsage talks about the **usage** but I didn't understand the "usage" thing... 

Please someone can explain by example.
Thank you very much for the package and time saving!

Leo.

**Comment by gerardojbaez** [comment]
Plan subscription "ends_at" attribute is the date when the subscription ends; for example, when the user has paid for 1 month of service and that month has passed. 

As for the "valid_until" attribute of a usage record, it is the date when a usage record needs to be reset. For example, let's say you have a Listings feature, a user has used 10 of them; assuming you have configured Listings to be reset every month, the next time the user uses the Listings feature and the valid_until date has been reached, the Listings usage count is [reset back to 0](https://github.com/gerardojbaez/laraplans/blob/6d0112d5219878f2bead55bb58b78f27f407a775/src/Laraplans/SubscriptionUsageManager.php#L41-L55), then increased as per your instructions when using [`record($feature)`](https://laraplans.readthedocs.io/en/latest/usage.html#record-feature-usage) method. This feature is optional and is only used when [`resettable_interval` and `resettable_count`](https://github.com/gerardojbaez/laraplans/blob/6d0112d5219878f2bead55bb58b78f27f407a775/src/config/laraplans.php#L50-L51) are set. I don't recall why exactly this feature was implemented but it seems unnecessary and redundant 🤔
