### ISSUE TITLE
FindEndingPeriod does not account for canceled subscription

### ISSUE THREAD

**Issue by samtoya** [gerardojbaez/laraplans#44]
/**
     * Find ending subscriptions.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFindEndingPeriod($query, $dayRange = 3)
    {
        $from = Carbon::now();
        $to = Carbon::now()->addDays($dayRange);

        $query->whereBetween('ends_at', [$from, $to]);
    }

Potential Fix: -->

public function scopeFindEndingPeriod($query, $dayRange = 3)
    {
        $from = Carbon::now();
        $to = Carbon::now()->addDays($dayRange);

        $query->whereBetween('ends_at', [$from, $to])->whereNull('canceled_at')->whereNull('canceled_immediately');
    }

**Comment by gerardojbaez** [comment]
I've added two new Eloquent scopes for excluding canceled subscriptions:

- Method `Gerardojbaez\Laraplans\Models\PlanSubscription::scopeExcludeCanceled`
- Method `Gerardojbaez\Laraplans\Models\PlanSubscription::scopeExcludeImmediatelyCanceled`

Using `findEndingPeriod($days)->excludeCanceled()` or `findEndingPeriod($days)->excludeImmediatelyCanceled()` should do the trick.
