### ISSUE TITLE
Carbon package version needs update in composer

### ISSUE THREAD

**Issue by pippos44** [gerardojbaez/laraplans#47]
Your requirements could not be resolved to an installable set of packages.
#
`Problem 1
    - Installation request for gerardojbaez/laraplans ^2.2 -> satisfiable by gerardojbaez/laraplans[v2.2.0].
    - gerardojbaez/laraplans v2.2.0 requires nesbot/carbon ~1.21 -> satisfiable by nesbot/carbon[1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2] but these conflict with your requirements or minimum-stability.`

**Comment by erayaydin** [comment]
:+1:

**Comment by samtoya** [comment]
+1

**Comment by marty12321** [comment]
+1, laravel 5.8 cannot install

**Comment by pippos44** [comment]
> +1, laravel 5.8 cannot install

Try installing laraplans manually for now. I have pull it down, changed the version to "nesbot/carbon": "~1.21" and update composer afterwards to pick up changes. I haven't noticed any issues yet but I can continue working with my project.

**Comment by mckenziearts** [comment]
> Try installing laraplans manually for now. I have pull it down, changed the version to "nesbot/carbon": "~1.21" and update composer afterwards to pick up changes. I haven't noticed any issues yet but I can continue working with my project.

I tried what you told but i can't install it on laravel 5.8, cause when i change "nesbot/carbon" version to "~1.21" i got this : 

```bash
Problem 1
    - Conclusion: remove laravel/framework v5.8.13
    - Conclusion: don't install laravel/framework v5.8.13
    - rennokki/plans 1.6.0 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev], illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - rennokki/plans 1.6.1 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev], illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - rennokki/plans 1.6.2 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - rennokki/plans 1.6.3 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.8.13].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.8.13].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.8.13].
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v5.8.13
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.8.13
```

**Comment by pippos44** [comment]
> > Try installing laraplans manually for now. I have pull it down, changed the version to "nesbot/carbon": "~1.21" and update composer afterwards to pick up changes. I haven't noticed any issues yet but I can continue working with my project.
> 
> I tried what you told but i can't install it on laravel 5.8, cause when i change "nesbot/carbon" version to "~1.21" i got this :
> 
> ```shell
> Problem 1
>     - Conclusion: remove laravel/framework v5.8.13
>     - Conclusion: don't install laravel/framework v5.8.13
>     - rennokki/plans 1.6.0 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev], illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - rennokki/plans 1.6.1 requires illuminate/support ~5.5.0|~5.6.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev], illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - rennokki/plans 1.6.2 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
>     - rennokki/plans 1.6.3 requires laravel/framework ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by laravel/framework[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
>     - Can only install one of: laravel/framework[5.6.x-dev, v5.8.13].
>     - Can only install one of: laravel/framework[5.7.x-dev, v5.8.13].
>     - Can only install one of: laravel/framework[5.5.x-dev, v5.8.13].
>     - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v5.8.13
>     - don't install illuminate/support v5.6.0|don't install laravel/framework v5.8.13
> ```

I assume you changed the dependancy in laraplans package and not the main carbon package?

{
    "name": "gerardojbaez/laraplans",
    "description": "SaaS style recurring plans for Laravel.",
    "keywords": ["plans", "laravel", "subscriptions", "memberships"],
    "license": "MIT",
    "type": "library",
    "require": {
        "php": ">=5.5.9",
        **"nesbot/carbon": "~1.21",**
        "illuminate/support": "~5.3",
        "illuminate/database": "~5.3"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "orchestra/testbench": "~3.3.0",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0"
    },
    "autoload": {
        "psr-4": {
            "Gerardojbaez\\Laraplans\\": "src/Laraplans/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ],
        "psr-4": {
            "Gerardojbaez\\Laraplans\\Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev"
}

**Comment by mckenziearts** [comment]
Okay let me try this time. I will download the laraplans package in my laravel project

**Comment by erayaydin** [comment]
This is temporary solution, package should fix requirements

**Comment by 1mursaleen** [comment]
Same problem. I've been using this package in many of my projects, my new laravel project is version 5.8 and this won't install with it. Kindly, update it as soon as possible. 

I don't understand the temporary solution you guys are discussing. how do I change the dependency **"nesbot/carbon": "~1.21"**  in laraplans package.

**Comment by siarheipashkevich** [comment]
@gerardojbaez any updates?
