### ISSUE TITLE
Purpose of the subscriptions name property

### ISSUE THREAD

**Issue by Konafets** [gerardojbaez/laraplans#5]
The doc says:

> The first argument passed to newSubscription method should be the name of the subscription. If your application offer a single subscription, you might call this main or primary. The second argument is the plan instance your user is subscribing to.

In my scenario I have multiple plans where a user can subscribe to. He can only subscribe to one plan at a time, so he will never have more than one subscription. Does this means, the name of the subscription can be just `primary`?

**Comment by gerardojbaez** [comment]
Subscription name is a unique identifier for a particular section in your application. For example, if you offer mutiple services under the same application, (maybe with separate billing), you may use the subscription name to indentify each. When only one subscription is needed, you can name it `primary` or `main`. Just like you have mentioned.

**Comment by Konafets** [comment]
Thanks!
