### ISSUE TITLE
Carbon 2?

### ISSUE THREAD

**Issue by siarheipashkevich** [gerardojbaez/laraplans#53]
Could you please add carbon 2 to your package instead carbon 1?

**Comment by siarheipashkevich** [comment]
@gerardojbaez any updates?

**Comment by sagitarius29** [comment]
@siarheipashkevich  Hello, this package is not updated since 26 september, i hope that your petition will be implemented.

**Comment by sagitarius29** [comment]
@siarheipashkevich you can to send your PR ?

**Comment by siarheipashkevich** [comment]
@sagitarius29 sorry but I can't. Maybe you can do this PR?
