### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by siarheipashkevich** [gerardojbaez/laraplans#57]

**Comment by techguydev** [comment]
is Laravel 7 support planned?

**Comment by siarheipashkevich** [comment]
@lmatab IMHO no. But I found a good fork and using it in my project.
https://github.com/czechbox/laravelplans

**Comment by techguydev** [comment]
@siarheipashkevich  Thanks a lot for sharing the fork, I will test it out.
